import { chromium } from '@playwright/test';
import assert from 'node:assert/strict';
import fs from 'node:fs/promises';
import path from 'node:path';

const executablePath = process.env.PLAYWRIGHT_CHROMIUM_EXECUTABLE;
const browser = await chromium.launch({ headless: true, ...(executablePath && { executablePath }) });
const page = await browser.newPage({ viewport: { width: 1440, height: 1080 }, deviceScaleFactor: 1 });
const errors = [];
page.on('pageerror', error => errors.push(error.message));
await fs.mkdir('test-results', { recursive: true });
await page.goto(process.env.CLARA_BASE_URL || 'http://127.0.0.1:5173');
await page.getByRole('heading', { name: 'Tu dinero, bajo control.' }).waitFor();
await page.waitForTimeout(1300);
await page.screenshot({ path: 'test-results/desktop.png', fullPage: true });
assert.equal(await page.locator('body').evaluate(e => e.scrollWidth > innerWidth), false, 'Desktop overflows');

await page.getByRole('button', { name: 'Añadir gasto', exact: true }).first().click();
await page.getByLabel('Nombre del gasto').fill('Prueba seguro anual');
await page.getByLabel('Importe de cada pago').fill('240');
await page.getByLabel('Frecuencia').selectOption('yearly');
await page.getByLabel('Ya reservado al inicio').fill('100');
await page.getByRole('button', { name: 'Guardar gasto' }).click();
await page.getByRole('button', { name: 'Mis gastos' }).click();
await page.getByLabel('Buscar gastos').fill('Prueba seguro');
await page.getByRole('button', { name: 'Prueba seguro anual', exact: true }).click();
assert.equal(await page.getByLabel('Importe de cada pago').inputValue(), '240');
await page.getByLabel('Importe de cada pago').fill('360');
await page.getByRole('button', { name: 'Guardar gasto' }).click();
await page.reload();
await page.getByRole('button', { name: 'Mis gastos' }).click();
await page.getByLabel('Buscar gastos').fill('Prueba seguro');
await page.getByText('360,00').first().waitFor();
await page.getByRole('button', { name: 'Prueba seguro anual', exact: true }).click();
await page.getByRole('button', { name: 'Eliminar', exact: true }).click();
await page.getByRole('button', { name: 'Eliminar gasto', exact: true }).click();
await page.getByText('No hay gastos aquí todavía').waitFor();

await page.getByRole('button', { name: 'Configuración', exact: true }).click();
await page.getByLabel('Ingresos netos mensuales').fill('3200');
await page.getByRole('button', { name: 'Guardar mi plan' }).click();
await page.getByRole('button', { name: 'Vista general', exact: true }).click();
const incomeText = await page.locator('.metric-card').first().innerText();
assert.match(incomeText, /3200|3.200/);
await page.getByRole('button', { name: 'Calendario', exact: true }).click();
await page.getByRole('button', { name: 'Marcar pagado: Alquiler de casa' }).click();
await page.getByRole('button', { name: 'Marcar pendiente: Alquiler de casa' }).waitFor();
await page.getByRole('button', { name: 'Mes siguiente' }).click();
await page.getByRole('button', { name: 'Mes anterior' }).click();
await page.getByRole('button', { name: 'Marcar pendiente: Alquiler de casa' }).waitFor();
await page.screenshot({ path: 'test-results/calendar.png', fullPage: true });

await page.getByRole('button', { name: 'Previsión', exact: true }).click();
await page.getByLabel('Gasto mensual adicional').fill('500');
assert.match(await page.locator('.simulator').innerText(), /500/);
await page.getByRole('button', { name: 'Mis reservas', exact: true }).click();
await page.getByRole('heading', { name: 'Seguro del coche', exact: true }).waitFor();
await page.getByRole('button', { name: 'Configuración', exact: true }).click();
const downloadEvent = page.waitForEvent('download');
await page.getByRole('button', { name: 'Descargar copia', exact: true }).click();
const download = await downloadEvent;
await download.saveAs('test-results/backup.json');
const backup = JSON.parse(await fs.readFile('test-results/backup.json', 'utf8'));
assert.equal(backup.income, 3200);
await page.locator('input[type=file]').setInputFiles(path.resolve('test-results/backup.json'));
await page.getByRole('button', { name: 'Restaurar copia', exact: true }).click();
await page.getByRole('button', { name: 'Empezar de cero', exact: true }).click();
await page.getByRole('button', { name: 'Crear mi plan', exact: true }).click();
assert.equal(await page.getByLabel('Ingresos netos mensuales').inputValue(), '0');
await page.getByRole('button', { name: 'Vista general', exact: true }).click();
await page.getByText('No hay gastos aquí todavía').waitFor();

await page.evaluate(() => localStorage.clear());
await page.reload();
await page.setViewportSize({ width: 390, height: 844 });
await page.waitForTimeout(600);
await page.screenshot({ path: 'test-results/mobile.png', fullPage: true });
assert.equal(await page.locator('body').evaluate(e => e.scrollWidth > innerWidth), false, 'Mobile overflows');
await page.getByRole('button', { name: 'Abrir menú' }).click();
await page.getByRole('button', { name: 'Calendario', exact: true }).click();
await page.screenshot({ path: 'test-results/mobile-calendar.png', fullPage: true });
assert.equal(await page.locator('body').evaluate(e => e.scrollWidth > innerWidth), false, 'Mobile calendar overflows');
await page.getByRole('button', { name: 'Añadir gasto', exact: true }).first().click();
await page.getByRole('dialog').waitFor();
await page.keyboard.press('Escape');
assert.equal(await page.getByRole('dialog').count(), 0);
assert.deepEqual(errors, [], 'Browser runtime errors');
console.log('Browser checks passed: CRUD, persistence, settings, paid status, month navigation, forecast, reserves, export/import, reset, responsive layouts, modal keyboard, no runtime errors.');
await browser.close();
