import React, { useEffect, useMemo, useRef, useState } from 'react';
import { Area, AreaChart, CartesianGrid, ResponsiveContainer, Tooltip, XAxis, YAxis, PieChart, Pie, Cell } from 'recharts';
import { ArrowDownLeft, ArrowDownToLine, ArrowRight, ArrowUpRight, Bell, CalendarDays, Check, CheckCheck, ChevronLeft, ChevronRight, CircleHelp, CreditCard, Download, Ellipsis, Flower2, Home, LayoutDashboard, Leaf, Menu, Plus, Search, Settings2, ShieldCheck, Sparkles, TrendingUp, Wallet, X, Zap, Wifi, Music2, Tv, Dumbbell, Car, Droplets, Pencil, Trash2, Upload, AlertTriangle, RotateCcw } from 'lucide-react';
import { addMonths, categories, colors, demoData, dueDate, euro, forecast, frequencyLabels, intervals, monthKey, monthLabel, monthlyReserve, validateData } from './finance';

const STORAGE = 'clara-finances-v1';
const navigation = [{ id: 'overview', label: 'Vista general', icon: LayoutDashboard }, { id: 'expenses', label: 'Mis gastos', icon: CreditCard }, { id: 'calendar', label: 'Calendario', icon: CalendarDays }, { id: 'forecast', label: 'Previsión', icon: TrendingUp }, { id: 'reserves', label: 'Mis reservas', icon: ShieldCheck }];
const expenseIcons = { Vivienda: Home, Suministros: Zap, Suscripciones: Music2, Transporte: Car, Salud: Dumbbell, Seguros: ShieldCheck, Otros: Wallet };
function initialData() { try { const raw = localStorage.getItem(STORAGE); if (raw) { const parsed = JSON.parse(raw); if (validateData(parsed)) return parsed; } } catch {} return demoData(); }
function ExpenseIcon({ expense }) { const Icon = expense.id === 'internet' ? Wifi : expense.id === 'netflix' ? Tv : expense.id === 'water' ? Droplets : expenseIcons[expense.category] || Wallet; return <span className={`expense-icon cat-${expense.category}`}><Icon size={18} /></span>; }
function Modal({ title, subtitle, onClose, children }) {
  const ref = useRef();
  useEffect(() => { const previous = document.activeElement; const node = ref.current; node?.focus(); const handler = e => { if (e.key === 'Escape') onClose(); if (e.key === 'Tab') { const items = [...node.querySelectorAll('button, input, select, textarea, a[href]')].filter(el => !el.disabled); const first = items[0], last = items.at(-1); if (e.shiftKey && (document.activeElement === first || document.activeElement === node)) { e.preventDefault(); last?.focus(); } else if (!e.shiftKey && document.activeElement === last) { e.preventDefault(); first?.focus(); } } }; document.addEventListener('keydown', handler); document.body.style.overflow = 'hidden'; return () => { document.removeEventListener('keydown', handler); document.body.style.overflow = ''; previous?.focus(); }; }, []);
  return <div className="modal-backdrop" onClick={e => e.target === e.currentTarget && onClose()}><section ref={ref} tabIndex={-1} role="dialog" aria-modal="true" aria-labelledby="modal-title" className="modal"><button className="icon-button modal-close" aria-label="Cerrar" onClick={onClose}><X size={20} /></button><span className="eyebrow">TU DINERO, CON CLARIDAD</span><h2 id="modal-title">{title}</h2>{subtitle && <p className="muted modal-subtitle">{subtitle}</p>}{children}</section></div>;
}
function ExpenseForm({ expense, startMonth, onSave, onClose, onDelete }) {
  const [form, setForm] = useState(expense || { name: '', amount: '', category: 'Suscripciones', frequency: 'monthly', day: 1, start: startMonth, end: '', fund: 0 });
  const field = (key, value) => setForm(f => ({ ...f, [key]: value }));
  return <Modal title={expense ? 'Los detalles de tu gasto' : 'Un gasto previsto, una sorpresa menos.'} subtitle="Añádelo una vez. Clara lo tendrá en cuenta en los próximos meses." onClose={onClose}><form onSubmit={e => { e.preventDefault(); onSave({ ...form, id: form.id || crypto.randomUUID(), name: form.name.trim(), amount: Number(form.amount), day: Number(form.day), fund: intervals[form.frequency] > 1 ? Number(form.fund) : 0 }); }}><label>Nombre del gasto<input autoFocus required pattern=".*\S.*" title="Escribe un nombre para el gasto" maxLength={100} value={form.name} onChange={e => field('name', e.target.value)} placeholder="Ej. Seguro del coche" /></label><div className="form-grid"><label>Importe de cada pago (€)<input type="number" min="0.01" max="100000000" step="0.01" required value={form.amount} onChange={e => field('amount', e.target.value)} placeholder="0,00" /></label><label>Frecuencia<select value={form.frequency} onChange={e => field('frequency', e.target.value)}>{Object.entries(frequencyLabels).map(([key, label]) => <option key={key} value={key}>{label}</option>)}</select></label><label>Categoría<select value={form.category} onChange={e => field('category', e.target.value)}>{categories.map(c => <option key={c}>{c}</option>)}</select></label><label>Día de cobro<input type="number" min="1" max="31" required value={form.day} onChange={e => field('day', e.target.value)} /></label><label>{intervals[form.frequency] > 1 ? 'Primer vencimiento del plan' : 'Primer mes de cobro'}<input type="month" required value={form.start} onChange={e => field('start', e.target.value)} /></label><label>Último mes (opcional)<input type="month" min={form.start} value={form.end || ''} onChange={e => field('end', e.target.value)} /></label></div>{intervals[form.frequency] > 1 && <div className="reserve-form"><label>Ya reservado al inicio del plan (€)<input type="number" min="0" max="100000000" step="0.01" required value={form.fund} onChange={e => field('fund', e.target.value)} /></label><p><ShieldCheck size={16} /> Reservarás {euro(monthlyReserve({ ...form, amount: Number(form.amount) }), 2)} al mes. Si no basta para el próximo pago, añadiremos la diferencia a ese mes.</p></div>}<div className="modal-actions">{expense && <button type="button" className="button danger-ghost" onClick={() => onDelete(expense)}><Trash2 size={16} /> Eliminar</button>}<button type="button" className="button secondary" onClick={onClose}>Cancelar</button><button type="submit" className="button primary"><Check size={17} /> Guardar gasto</button></div></form></Modal>;
}
function ChartTooltip({ active, payload, label }) { if (!active || !payload?.length) return null; return <div className="chart-tooltip"><strong className="capitalize">{label}</strong>{payload.map(p => <div key={p.dataKey}><span style={{ background: p.color }} />{p.name}<b>{euro(p.value, 2)}</b></div>)}</div>; }

export default function App() {
  const [data, setData] = useState(initialData);
  const [page, setPage] = useState('overview');
  const [offset, setOffset] = useState(0);
  const [modal, setModal] = useState(null);
  const [editing, setEditing] = useState(null);
  const [query, setQuery] = useState('');
  const [category, setCategory] = useState('Todas');
  const [range, setRange] = useState(6);
  const [toast, setToast] = useState('');
  const [storageError, setStorageError] = useState(false);
  const [mobileOpen, setMobileOpen] = useState(false);
  const [simulation, setSimulation] = useState(0);
  const [calendarDay, setCalendarDay] = useState(null);
  const fileRef = useRef();
  useEffect(() => { try { localStorage.setItem(STORAGE, JSON.stringify(data)); setStorageError(false); } catch { setStorageError(true); } }, [data]);
  useEffect(() => { if (!toast) return; const timer = setTimeout(() => setToast(''), 4500); return () => clearTimeout(timer); }, [toast]);
  const months = useMemo(() => forecast(data, 24), [data]);
  const current = months[offset];
  const month = current.key;
  const due = current.items.filter(e => e.due).sort((a, b) => a.day - b.day);
  const pending = due.filter(e => !data.paid[`${month}:${e.id}`]);
  const annuals = data.expenses.filter(e => intervals[e.frequency] > 1);
  const upcoming = months.slice(offset, offset + 3).flatMap(m => m.items.filter(e => e.due && intervals[e.frequency] > 1).map(e => ({ ...e, month: m.key })));
  const alerts = months.slice(offset, offset + 3).filter(m => m.shortfall > 0 || m.available < 0);
  const categoryData = categories.map(name => ({ name, value: current.items.filter(e => e.category === name).reduce((sum, e) => sum + ((e.frequency === 'monthly' || e.frequency === 'once') && e.due ? e.amount : e.reserve + e.gap), 0) })).filter(c => c.value > 0);
  const expenseTotal = current.fixed + current.provision + current.shortfall;
  const changePage = id => { setPage(id); setMobileOpen(false); setCalendarDay(null); };
  const notify = message => setToast(message);
  const updateData = updater => setData(previous => ({ ...updater(previous), demo: false }));
  const saveExpense = expense => { updateData(d => ({ ...d, expenses: editing ? d.expenses.map(e => e.id === expense.id ? expense : e) : [...d.expenses, expense] })); setModal(null); notify(editing ? 'Gasto actualizado. Previsión recalculada.' : 'Gasto añadido a tu previsión.'); };
  const openExpense = (expense = null) => { setEditing(expense); setModal('expense'); };
  const markPaid = e => { updateData(d => ({ ...d, paid: { ...d.paid, [`${month}:${e.id}`]: !d.paid[`${month}:${e.id}`] } })); };
  const exportData = () => { const url = URL.createObjectURL(new Blob([JSON.stringify(data, null, 2)], { type: 'application/json' })); const a = document.createElement('a'); a.href = url; a.download = `clara-copia-${monthKey(new Date())}.json`; a.click(); setTimeout(() => URL.revokeObjectURL(url), 1000); notify('Copia de seguridad descargada.'); };
  const importData = async e => { const file = e.target.files[0]; if (!file) return; try { if (file.size > 2000000) throw new Error(); const parsed = JSON.parse(await file.text()); if (!validateData(parsed)) throw new Error(); setEditing(parsed); setModal('import'); } catch { notify('El archivo no es una copia válida de Clara.'); } e.target.value = ''; };
  const visibleExpenses = data.expenses.filter(e => e.name.toLocaleLowerCase('es').includes(query.toLocaleLowerCase('es')) && (category === 'Todas' || e.category === category));
  const MonthPicker = () => <div className="month-picker"><button className="icon-button" aria-label="Mes anterior" disabled={offset === 0} onClick={() => { setOffset(v => v - 1); setCalendarDay(null); }}><ChevronLeft size={17} /></button><CalendarDays size={16} /><span className="capitalize">{monthLabel(month)}</span><button className="icon-button" aria-label="Mes siguiente" disabled={offset === 12} onClick={() => { setOffset(v => v + 1); setCalendarDay(null); }}><ChevronRight size={17} /></button></div>;
  const forecastChart = (full = false) => <div className={`chart-wrap ${full ? 'chart-tall' : ''}`}><ResponsiveContainer width="100%" height="100%"><AreaChart data={months.slice(offset, offset + (full ? 12 : range))} margin={{ top: 15, right: 10, left: -16, bottom: 0 }}><defs><linearGradient id="availableGradient" x1="0" y1="0" x2="0" y2="1"><stop offset="0%" stopColor="#badc8b" stopOpacity={0.55} /><stop offset="100%" stopColor="#badc8b" stopOpacity={0.03} /></linearGradient></defs><CartesianGrid vertical={false} stroke="#eaece7" strokeDasharray="3 5" /><XAxis dataKey="name" axisLine={false} tickLine={false} tick={{ fill: '#899088', fontSize: 11 }} dy={10} /><YAxis axisLine={false} tickLine={false} tick={{ fill: '#899088', fontSize: 10 }} tickFormatter={v => `${v.toLocaleString('es-ES')} €`} /><Tooltip content={<ChartTooltip />} /><Area type="monotone" dataKey="income" name="Ingresos" stroke="#b9beb5" strokeDasharray="5 5" strokeWidth={1.5} fill="none" /><Area type="monotone" dataKey="committed" name="Comprometido" stroke="#dbb97c" strokeWidth={2} fill="none" /><Area type="monotone" dataKey="available" name="Disponible" stroke="#537b45" strokeWidth={3} fill="url(#availableGradient)" activeDot={{ r: 6, fill: '#234c3c', stroke: '#fff', strokeWidth: 3 }} /></AreaChart></ResponsiveContainer></div>;
  const expenseTable = (items, compact = false) => <div className="table-scroll"><table><thead><tr><th>Gasto</th>{!compact && <th>Categoría</th>}<th>Frecuencia</th><th>{compact ? 'Cobro' : 'Próximo cobro'}</th><th className="align-right">Importe</th><th aria-label="Acciones" /></tr></thead><tbody>{items.map(e => { const next = months.slice(offset).find(m => m.items.some(i => i.id === e.id && i.due)); return <tr key={e.id}><td><button className="expense-name" onClick={() => openExpense(e)}><ExpenseIcon expense={e} /><span>{e.name}{compact && <small>{e.category}</small>}</span></button></td>{!compact && <td><span className="category-tag">{e.category}</span></td>}<td><span className={`frequency-tag ${e.frequency !== 'monthly' ? 'frequency-special' : ''}`}>{frequencyLabels[e.frequency]}</span></td><td className="muted">{next ? dueDate(e, next.key).toLocaleDateString('es-ES', { day: 'numeric', month: 'short' }) : 'Fuera del horizonte'}</td><td className="align-right amount">{euro(e.amount, 2)}</td><td><button className="icon-button" title={`Editar ${e.name}`} aria-label={`Editar ${e.name}`} onClick={() => openExpense(e)}><Ellipsis size={19} /></button></td></tr>; })}</tbody></table>{!items.length && <div className="empty-state"><Search size={28} /><h3>No hay gastos aquí todavía</h3><p>Añade un gasto o prueba con otro filtro.</p><button className="button secondary" onClick={() => openExpense()}>Añadir gasto</button></div>}</div>;

  return <div className="app-shell"><aside className={`sidebar ${mobileOpen ? 'sidebar-open' : ''}`}><a className="brand" href="#" onClick={e => { e.preventDefault(); changePage('overview'); }}><span className="brand-mark">✳</span>clara<span className="brand-dot">.</span></a><p className="brand-caption">TU DINERO, CON CLARIDAD</p><div className="workspace-label">MI ESPACIO</div><nav>{navigation.map(({ id, label, icon: Icon }) => <button key={id} className={`nav-item ${page === id ? 'active' : ''}`} onClick={() => changePage(id)}><Icon size={19} /><span>{label}</span>{id === 'expenses' && <span className="nav-count">{data.expenses.length}</span>}{id === 'overview' && <span className="active-dot" />}</button>)}</nav><div className="sidebar-bottom"><div className="sidebar-note"><span className="note-art"><Leaf size={29} /><Sparkles size={14} /></span><h3>La tranquilidad<br />también se planifica.</h3><p>Un pequeño hábito hoy.<br />Más libertad mañana.</p><button onClick={() => setModal('method')}>Así funciona Clara <ArrowUpRight size={14} /></button></div><button className={`nav-item ${page === 'settings' ? 'active' : ''}`} onClick={() => changePage('settings')}><Settings2 size={19} />Configuración</button><div className="profile"><span className="avatar">Tú</span><div><strong>Mi espacio personal</strong><small><span className="status-dot" /> Guardado en este dispositivo</small></div></div></div></aside>{mobileOpen && <div className="sidebar-scrim" onClick={() => setMobileOpen(false)} />}
  <div className="main-shell"><header className="topbar"><div className="breadcrumb"><button className="icon-button mobile-menu" aria-label="Abrir menú" onClick={() => setMobileOpen(true)}><Menu size={21} /></button><span>Mi espacio</span><ChevronRight size={13} /><strong>{navigation.find(n => n.id === page)?.label || 'Configuración'}</strong></div><div className="topbar-right"><span className="local-badge"><span className="status-dot" /> Espacio personal</span><button className="icon-button notification-button" onClick={() => setModal('alerts')} aria-label="Ver avisos"><Bell size={19} />{alerts.length > 0 && <i />}</button><span className="avatar top-avatar">Tú</span></div></header>
  <main><div className="page-heading"><div><div className="eyebrow">UN POCO DE ORDEN. MUCHA TRANQUILIDAD.</div><h1>{page === 'overview' ? <>Tu dinero, bajo control<span className="heading-dot">.</span></> : page === 'expenses' ? 'Cada gasto, en su sitio.' : page === 'calendar' ? 'Adelántate a cada cobro.' : page === 'forecast' ? 'Mira lo que viene.' : page === 'reserves' ? 'Tu tranquilidad, mes a mes.' : 'Hagámoslo tuyo.'}</h1><p className="page-description">{page === 'overview' ? 'Sabe lo que viene. Disfruta de lo que queda.' : page === 'expenses' ? 'Tus pagos recurrentes y puntuales, en un único lugar.' : page === 'calendar' ? 'Todos tus vencimientos, sin perder de vista ninguno.' : page === 'forecast' ? 'Doce meses por delante para decidir con perspectiva.' : page === 'reserves' ? 'Pequeñas reservas para que los grandes pagos no sorprendan.' : 'Ajusta las cifras que dan forma a tu previsión.'}</p></div><div className="heading-actions">{page !== 'settings' && <MonthPicker />}<button className="button primary" onClick={() => openExpense()}><Plus size={17} /> Añadir gasto</button></div></div>
  {storageError && <div className="notice warning"><AlertTriangle size={17} /> No se han podido guardar los cambios. Descarga una copia antes de cerrar.<button onClick={exportData}>Descargar copia</button></div>}
  {data.demo && <div className="demo-banner"><span><Sparkles size={15} /> Estás explorando con datos de ejemplo. Tu tranquilidad empieza con tus cifras.</span><button onClick={() => setModal('start')}>Configurar mi plan <ArrowRight size={14} /></button></div>}
  {page === 'overview' && <><section className="summary-grid"><article className={`available-card ${current.available < 0 ? 'negative' : ''}`}><div className="hero-orbit orbit-one" /><div className="hero-orbit orbit-two" /><div className="hero-orbit orbit-three" /><div className="available-top"><span><span className="tiny-spark">✳</span> TU DISPONIBLE REAL</span><button className="icon-button" aria-label="Cómo se calcula el disponible" onClick={() => setModal('method')}><CircleHelp size={17} /></button></div><div className="available-value">{euro(current.available, 2)}</div><p>para gastar, ahorrar o invertir este mes</p><div className="available-bottom"><span><ShieldCheck size={14} /> Después de cubrir tu plan</span><ArrowUpRight size={21} /></div></article><article className="metric-card"><div className="metric-icon mint"><ArrowDownLeft size={20} /></div><span className="metric-label">Ingresos del mes</span><strong>{euro(current.income, 2)}</strong><button className="metric-footer" onClick={() => changePage('settings')}><span className="status-dot" />Tu ingreso mensual previsto <ArrowUpRight size={14} /></button></article><article className="metric-card"><div className="metric-icon peach"><CreditCard size={19} /></div><span className="metric-label">Gastos previstos</span><strong>{euro(expenseTotal, 2)}</strong><span className="metric-footer">{data.expenses.length} gastos · reservas incluidas</span></article><article className="metric-card"><div className="metric-icon lavender"><ShieldCheck size={20} /></div><span className="metric-label">Tu colchón protegido</span><strong>{euro(current.cushion, 2)}</strong><button className="metric-footer" onClick={() => changePage('settings')}><span className="small-pill">A TU RITMO</span> Ajustar <ArrowUpRight size={13} /></button></article></section>
  <div className={`notice ${alerts.length ? 'warning' : ''}`}><span className="notice-icon">{alerts.length ? <AlertTriangle size={19} /> : <ShieldCheck size={19} />}</span><div><strong>{alerts.length ? 'Hay un mes que necesita tu atención.' : 'Lo previsto da tranquilidad.'}</strong><span>{alerts.length ? `${monthLabel(alerts[0].key)}: ${alerts[0].shortfall > 0 ? `${euro(alerts[0].shortfall, 2)} extra para completar reservas` : `${euro(Math.abs(alerts[0].available), 2)} de déficit previsto`}.` : upcoming.length ? `El próximo pago de ${upcoming[0].name.toLowerCase()} ya está contemplado en tu plan.` : 'Tus gastos registrados están contemplados en la previsión.'}</span></div><button onClick={() => changePage('reserves')}>Ver reservas <ArrowRight size={15} /></button></div>
  <section className="middle-grid"><article className="panel forecast-panel"><div className="panel-heading"><div><h2>Una mirada a los próximos meses</h2><p>Tu margen de libertad, mes a mes.</p></div><div className="segmented">{[6, 12].map(n => <button key={n} className={range === n ? 'selected' : ''} onClick={() => setRange(n)}>{n} meses</button>)}</div></div><div className="chart-legend"><span><i className="legend-dot green" />Disponible</span><span><i className="legend-dot sand" />Comprometido</span><span><i className="legend-line" />Ingresos</span></div>{forecastChart()}<div className="chart-bottom"><span><span className="status-dot" /> Incluye gastos, reservas, presupuesto diario y colchón</span><button onClick={() => changePage('forecast')}>Explorar previsión <ArrowUpRight size={14} /></button></div></article><article className="panel distribution-panel"><div className="panel-heading"><div><h2>¿Dónde va tu dinero?</h2><p>Cada euro tiene su lugar.</p></div><span className="subtle-icon"><Wallet size={18} /></span></div><div className="donut-container"><ResponsiveContainer width="100%" height="100%"><PieChart><Pie data={categoryData.length ? categoryData : [{ name: 'Sin gastos', value: 1 }]} dataKey="value" innerRadius={63} outerRadius={83} paddingAngle={3} cornerRadius={4} startAngle={90} endAngle={-270} stroke="none">{(categoryData.length ? categoryData : [{ name: 'Sin gastos' }]).map(c => <Cell key={c.name} fill={colors[c.name] || '#e8ece5'} />)}</Pie><Tooltip formatter={v => euro(categoryData.length ? v : 0, 2)} /></PieChart></ResponsiveContainer><div className="donut-label"><small>Total previsto</small><strong>{euro(expenseTotal)}</strong><span>este mes</span></div></div><div className="category-legend">{categoryData.slice(0, 4).map(c => <div key={c.name}><span><i style={{ background: colors[c.name] }} />{c.name}</span><b>{euro(c.value, 2)}</b></div>)}{categoryData.length > 4 && <div><span><i style={{ background: '#d8d6c6' }} />Otras categorías</span><b>{euro(categoryData.slice(4).reduce((s, c) => s + c.value, 0), 2)}</b></div>}</div></article></section>
  <section className="bottom-grid"><article className="panel expenses-panel"><div className="panel-heading"><div><h2>Tus gastos, sin sorpresas <span className="count-pill">{data.expenses.length}</span></h2><p>Lo recurrente, siempre a la vista.</p></div><button className="text-button" onClick={() => changePage('expenses')}>Ver todos <ArrowRight size={15} /></button></div>{expenseTable(data.expenses.slice(0, 5), true)}</article><article className="panel upcoming-panel"><div className="panel-heading"><div><h2>Próximos cobros</h2><p>Un vistazo a tu calendario del mes.</p></div><CalendarDays size={18} className="muted" /></div><div className="upcoming-list">{pending.slice(0, 4).map(e => <div className="upcoming-item" key={e.id}><div className="date-tile"><strong>{e.date.getDate()}</strong><span>{monthLabel(month, true).replace('.', '')}</span></div><div><strong>{e.name}</strong><small>{frequencyLabels[e.frequency]}</small></div><b>{euro(e.amount, 2)}</b></div>)}{!pending.length && <div className="mini-empty"><CheckCheck size={27} /><p>Todo al día.<br />No hay cobros pendientes este mes.</p></div>}</div><button className="full-width-link" onClick={() => changePage('calendar')}>Abrir mi calendario <ArrowRight size={15} /></button></article></section></>}
  {page === 'expenses' && <section className="panel"><div className="panel-heading expenses-toolbar"><div className="search-field"><Search size={17} /><input aria-label="Buscar gastos" placeholder="Buscar un gasto…" value={query} onChange={e => setQuery(e.target.value)} /></div><div className="filter-wrap"><select aria-label="Filtrar por categoría" value={category} onChange={e => setCategory(e.target.value)}><option>Todas</option>{categories.map(c => <option key={c}>{c}</option>)}</select><span className="muted">{visibleExpenses.length} gastos</span></div></div>{expenseTable(visibleExpenses)}<div className="table-footer">Los importes son por cobro. La previsión reparte los pagos anuales y trimestrales en reservas mensuales.</div></section>}
  {page === 'calendar' && <section className="calendar-layout"><article className="panel calendar-panel"><div className="panel-heading"><div><h2 className="capitalize">{monthLabel(month)}</h2><p>{due.length} cobros previstos · {euro(current.charges, 2)}</p></div><span className="category-tag">{due.length - pending.length} pagados</span></div><div className="calendar-grid">{['Lun', 'Mar', 'Mié', 'Jue', 'Vie', 'Sáb', 'Dom'].map(d => <div className="calendar-weekday" key={d}>{d}</div>)}{Array.from({ length: (new Date(`${month}-01T12:00:00`).getDay() + 6) % 7 }, (_, i) => <div className="calendar-blank" key={`blank${i}`} />)}{Array.from({ length: new Date(Number(month.slice(0, 4)), Number(month.slice(5)), 0).getDate() }, (_, i) => { const day = i + 1, items = due.filter(e => e.date.getDate() === day); const today = monthKey(new Date()) === month && new Date().getDate() === day; return <button key={day} className={`calendar-day ${today ? 'today' : ''} ${calendarDay === day ? 'day-selected' : ''}`} onClick={() => setCalendarDay(calendarDay === day ? null : day)} aria-label={`${day}: ${items.length} cobros`}><span>{day}</span>{items.slice(0, 2).map(e => <small key={e.id} style={{ '--event-color': colors[e.category] }}><i />{e.name}</small>)}{items.length > 2 && <small>+{items.length - 2} más</small>}{items.length > 0 && <b>{euro(items.reduce((s, e) => s + e.amount, 0))}</b>}</button>; })}</div></article><article className="panel calendar-detail"><div className="panel-heading"><div><h2>{calendarDay ? `Día ${calendarDay}` : 'Agenda del mes'}</h2><p>Marca los cobros que ya has pagado.</p></div></div><div className="agenda-list">{due.filter(e => !calendarDay || e.date.getDate() === calendarDay).map(e => <div className="agenda-item" key={e.id}><ExpenseIcon expense={e} /><div><strong>{e.name}</strong><small>Día {e.date.getDate()} · {euro(e.amount, 2)}</small></div><button className={`paid-toggle ${data.paid[`${month}:${e.id}`] ? 'is-paid' : ''}`} onClick={() => markPaid(e)} aria-label={`${data.paid[`${month}:${e.id}`] ? 'Marcar pendiente' : 'Marcar pagado'}: ${e.name}`} title={data.paid[`${month}:${e.id}`] ? 'Pagado' : 'Marcar pagado'}><Check size={17} /></button></div>)}{!due.filter(e => !calendarDay || e.date.getDate() === calendarDay).length && <div className="empty-state"><Leaf size={28} /><p>Un día sin cobros previstos.</p></div>}</div><p className="agenda-note">Marcar un cobro como pagado organiza tu agenda. El gasto ya está incluido en tu previsión y no se descuenta otra vez.</p></article></section>}
  {page === 'forecast' && <><section className="forecast-summary"><div><span>Disponible medio · próximos 12 meses</span><strong>{euro(months.slice(offset, offset + 12).reduce((s, m) => s + m.available, 0) / 12, 2)}</strong></div><div><span>Margen acumulado previsto</span><strong>{euro(months.slice(offset, offset + 12).reduce((s, m) => s + m.available, 0), 2)}</strong></div><div><span>Meses con déficit</span><strong>{months.slice(offset, offset + 12).filter(m => m.available < 0).length}<small> de 12</small></strong></div></section><article className="panel"><div className="panel-heading"><div><h2>El año, con perspectiva</h2><p>Previsión basada en tus ingresos y gastos registrados.</p></div><div className="chart-legend"><span><i className="legend-dot green" />Disponible</span><span><i className="legend-dot sand" />Comprometido</span></div></div>{forecastChart(true)}</article><article className="panel simulator"><div><span className="eyebrow">PRUEBA ANTES DE DECIDIR</span><h2>¿Y si cambias algo?</h2><p>Simula un nuevo gasto mensual y comprueba el margen que te dejaría.</p></div><div><label htmlFor="simulation">Gasto mensual adicional <strong>{euro(simulation)}</strong></label><input id="simulation" type="range" min="0" max="2000" step="10" value={simulation} onChange={e => setSimulation(Number(e.target.value))} /><div className="range-labels"><span>0 €</span><span>2.000 €</span></div></div><div className={current.available - simulation < 0 ? 'negative-text' : ''}><span>Te quedarían este mes</span><strong>{euro(current.available - simulation, 2)}</strong><small>Simulación · no modifica tu plan</small></div></article><article className="panel"><div className="panel-heading"><h2>Las cuentas, claras</h2></div><div className="table-scroll"><table className="forecast-table"><thead><tr><th>Mes</th><th>Ingresos</th><th>Gastos directos</th><th>Reservas + ajuste</th><th>Vida diaria</th><th>Colchón</th><th>Disponible</th></tr></thead><tbody>{months.slice(offset, offset + 12).map(m => <tr key={m.key}><td className="capitalize">{monthLabel(m.key)}</td><td>{euro(m.income)}</td><td>{euro(m.fixed, 2)}</td><td>{euro(m.provision + m.shortfall, 2)}{m.shortfall > 0 && <span title={`Incluye ${euro(m.shortfall, 2)} para completar reservas`} className="gap-dot"> *</span>}</td><td>{euro(m.variable)}</td><td>{euro(m.cushion)}</td><td className={`amount ${m.available < 0 ? 'negative-text' : 'positive-text'}`}>{euro(m.available, 2)}</td></tr>)}</tbody></table></div></article></>}
  {page === 'reserves' && <><div className="reserve-intro"><div className="reserve-intro-icon"><ShieldCheck size={32} /></div><div><h2>Los pagos grandes se preparan poco a poco.</h2><p>Clara aparta una parte cada mes para tus pagos trimestrales y anuales. El dinero reservado ya está excluido de tu disponible.</p></div><div><span>Aportación de este mes</span><strong>{euro(current.provision, 2)}</strong></div></div><div className="reserves-grid">{annuals.map(e => { const item = current.items.find(i => i.id === e.id); const next = months.slice(offset).find(m => m.items.some(i => i.id === e.id && i.due)); const nextItem = next?.items.find(i => i.id === e.id); return <article className="panel reserve-card" key={e.id}><div className="reserve-card-top"><ExpenseIcon expense={e} /><span className="frequency-tag frequency-special">{frequencyLabels[e.frequency]}</span><button className="icon-button" aria-label={`Editar ${e.name}`} onClick={() => openExpense(e)}><Pencil size={16} /></button></div><h2>{e.name}</h2><p>{next ? `Próximo pago: ${dueDate(e, next.key).toLocaleDateString('es-ES', { day: 'numeric', month: 'long', year: 'numeric' })}` : 'Sin pagos en los próximos meses'}</p><div className="reserve-amount"><strong>{euro(item.fundAfter, 2)}</strong><span> / {euro(e.amount)} del próximo pago</span></div><div className="progress-track"><div style={{ width: `${Math.min(100, item.fundAfter / e.amount * 100)}%` }} /></div><div className="reserve-detail"><span>Reserva mensual</span><b>{euro(item.reserve, 2)}</b></div>{nextItem?.gap > 0 ? <div className="reserve-status needs-attention"><AlertTriangle size={15} /> Faltarán {euro(nextItem.gap, 2)} en el vencimiento</div> : <div className="reserve-status"><ShieldCheck size={15} />{item.due ? 'Pago de este mes contemplado' : 'Próximo pago cubierto con el plan'}</div>}<small className="reserve-footnote">Saldo previsto al cierre de {monthLabel(month, true)}, después de los cobros.</small></article>; })}<button className="add-reserve" onClick={() => { setEditing(null); setModal('expense'); }}><span><Plus size={26} /></span><h3>Prepara tu próximo gran pago</h3><p>Añade un gasto anual o trimestral</p></button></div></>}
  {page === 'settings' && <Settings data={data} onSave={values => { updateData(d => ({ ...d, ...values })); setOffset(0); notify('Plan actualizado. Tus cuentas ya están recalculadas.'); }} onExport={exportData} onImport={() => fileRef.current.click()} onReset={() => setModal('reset')} />}
  <footer className="main-footer"><span><span className="footer-spark">✳</span> Menos sorpresas. Más vida.</span><span>Previsión orientativa con tus datos registrados <span className="footer-separator">·</span><button onClick={() => setModal('method')}>Cómo se calcula <CircleHelp size={13} /></button></span></footer></main></div>
  <input ref={fileRef} type="file" accept="application/json,.json" hidden onChange={importData} />
  {modal === 'expense' && <ExpenseForm expense={editing} startMonth={month} onSave={saveExpense} onClose={() => setModal(null)} onDelete={e => { setEditing(e); setModal('delete'); }} />}
  {modal === 'delete' && <Modal title={`¿Eliminar ${editing.name}?`} subtitle="Se quitará de todos los meses de tu previsión. Puedes volver a añadirlo cuando quieras." onClose={() => setModal(null)}><div className="modal-actions"><button className="button secondary" onClick={() => setModal('expense')}>Volver</button><button className="button danger" onClick={() => { updateData(d => ({ ...d, expenses: d.expenses.filter(e => e.id !== editing.id) })); setModal(null); notify('Gasto eliminado de la previsión.'); }}>Eliminar gasto</button></div></Modal>}
  {modal === 'method' && <Modal title="Lo que queda, de verdad." subtitle="El disponible es tu margen mensual planificado. Se calcula así:" onClose={() => setModal(null)}><div className="calculation"><div><span>Ingresos previstos</span><b>{euro(current.income, 2)}</b></div><div><span>− Gastos mensuales y puntuales</span><b>{euro(current.fixed, 2)}</b></div><div><span>− Reservas para pagos periódicos</span><b>{euro(current.provision, 2)}</b></div><div><span>− Dinero que falta en las reservas</span><b>{euro(current.shortfall, 2)}</b></div><div><span>− Presupuesto de vida diaria</span><b>{euro(current.variable, 2)}</b></div><div><span>− Colchón de seguridad mensual</span><b>{euro(current.cushion, 2)}</b></div><div className="calculation-total"><span>Tu disponible</span><b>{euro(current.available, 2)}</b></div></div><p className="help-copy">Las reservas empiezan en {monthLabel(data.startMonth)}. Los pagos anuales y trimestrales se cubren con lo reservado; si no alcanza, la diferencia reduce el disponible del mes del cobro. El saldo ya reservado se considera dinero separado de tus ingresos.</p><p className="help-copy">Clara no se conecta a tu banco: el disponible no es tu saldo bancario ni incluye movimientos que no hayas registrado. El presupuesto diario cubre tus gastos variables; ajústalo si cambian. Las alertas aparecen al abrir la aplicación, sin notificaciones externas.</p></Modal>}
  {modal === 'alerts' && <Modal title="Nada fuera de tu radar." subtitle="Avisos de los próximos tres meses del periodo seleccionado." onClose={() => setModal(null)}><div className="alerts-list">{alerts.map(m => <div className="alert-item" key={m.key}><AlertTriangle size={20} /><div><h3 className="capitalize">{monthLabel(m.key)}</h3>{m.shortfall > 0 && <p>Necesitarás {euro(m.shortfall, 2)} adicionales para completar tus reservas. Ya están descontados de la previsión.</p>}{m.available < 0 && <p>El plan supera tus ingresos en {euro(Math.abs(m.available), 2)}. Revisa los gastos o el presupuesto.</p>}</div></div>)}{upcoming.map(e => <div className="alert-item calm" key={`${e.id}-${e.month}`}><CalendarDays size={20} /><div><h3>{e.name} · {euro(e.amount, 2)}</h3><p>Vence el {dueDate(e, e.month).toLocaleDateString('es-ES', { day: 'numeric', month: 'long' })}. {e.gap > 0 ? 'Requiere completar la reserva.' : 'Contemplado con tus reservas previstas.'}</p></div></div>)}{!alerts.length && !upcoming.length && <div className="empty-state"><ShieldCheck size={32} /><h3>Todo en orden por aquí</h3><p>No hay avisos especiales para este periodo.</p></div>}</div></Modal>}
  {(modal === 'start' || modal === 'reset') && <Modal title={modal === 'start' ? 'Tu plan empieza aquí.' : 'Empezar con una hoja en blanco.'} subtitle="Se quitarán los gastos de ejemplo o los que tengas guardados. Después podrás configurar tus ingresos y añadir tus gastos." onClose={() => setModal(null)}><div className="onboarding-note"><Leaf size={24} /><p>Necesitas tres cosas: tus ingresos mensuales, tus gastos recurrentes y lo que quieres proteger cada mes.</p></div><div className="modal-actions"><button className="button secondary" onClick={exportData}><Download size={16} /> Guardar copia</button><button className="button primary" onClick={() => { setData({ version: 1, demo: false, startMonth: monthKey(new Date()), income: 0, variable: 0, cushion: 0, expenses: [], paid: {} }); setOffset(0); setModal(null); changePage('settings'); notify('Tu espacio está listo. Empieza por tus ingresos.'); }}>Crear mi plan <ArrowRight size={16} /></button></div></Modal>}
  {modal === 'import' && <Modal title="Restaurar tu copia" subtitle={`La copia contiene ${editing.expenses.length} gastos y sustituirá el plan guardado en este navegador.`} onClose={() => setModal(null)}><div className="modal-actions"><button className="button secondary" onClick={() => setModal(null)}>Cancelar</button><button className="button primary" onClick={() => { setData(editing); setOffset(0); setModal(null); notify('Copia restaurada correctamente.'); }}>Restaurar copia</button></div></Modal>}
  {toast && <div className="toast" role="status"><Check size={17} />{toast}<button aria-label="Cerrar aviso" onClick={() => setToast('')}><X size={15} /></button></div>}
  </div>;
}

function Settings({ data, onSave, onExport, onImport, onReset }) {
  const [values, setValues] = useState({ income: data.income, variable: data.variable, cushion: data.cushion, startMonth: data.startMonth });
  useEffect(() => { setValues({ income: data.income, variable: data.variable, cushion: data.cushion, startMonth: data.startMonth }); }, [data.income, data.variable, data.cushion, data.startMonth]);
  return <div className="settings-layout"><article className="panel settings-panel"><div className="panel-heading"><div><h2>La base de tu plan</h2><p>Estas cifras se aplican a cada mes de la previsión.</p></div><Settings2 size={21} /></div><form onSubmit={e => { e.preventDefault(); onSave({ ...values, income: Number(values.income), variable: Number(values.variable), cushion: Number(values.cushion) }); }}><label>Ingresos netos mensuales (€)<span className="field-description">El dinero que esperas recibir cada mes.</span><input required type="number" min="0" max="100000000" step="0.01" value={values.income} onChange={e => setValues({ ...values, income: e.target.value })} /></label><label>Presupuesto de vida diaria (€)<span className="field-description">Comida, ocio, compras y otros gastos variables del mes.</span><input required type="number" min="0" max="100000000" step="0.01" value={values.variable} onChange={e => setValues({ ...values, variable: e.target.value })} /></label><label>Colchón de seguridad mensual (€)<span className="field-description">Una cantidad que proteges cada mes para imprevistos.</span><input required type="number" min="0" max="100000000" step="0.01" value={values.cushion} onChange={e => setValues({ ...values, cushion: e.target.value })} /></label><label>Inicio de la previsión<input required type="month" value={values.startMonth} onChange={e => setValues({ ...values, startMonth: e.target.value })} /><span className="field-description">Si cambias el inicio, actualiza también el saldo inicial de tus reservas.</span></label><button className="button primary" type="submit"><Check size={17} /> Guardar mi plan</button></form></article><div className="settings-aside"><article className="panel"><span className="metric-icon mint"><ShieldCheck size={23} /></span><h2>Tus datos se quedan contigo.</h2><p>Tu plan se guarda en este navegador. No se sincroniza entre dispositivos. Descarga una copia para conservarlo si borras los datos del navegador.</p><button className="button secondary" onClick={onExport}><ArrowDownToLine size={17} /> Descargar copia</button><button className="button secondary" onClick={onImport}><Upload size={17} /> Importar copia</button></article><article className="panel reset-panel"><h2>Un nuevo comienzo</h2><p>Borra el plan actual y vuelve a organizar tus cuentas.</p><button className="text-button" onClick={onReset}><RotateCcw size={16} /> Empezar de cero</button></article></div></div>;
}
